name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm build, install
      run: |
        git clone "https://github.com/phantomdev-github/Guardian.git"
        cd ./Guardian
        npm i
    - name: npm build, install
      run: |
        git clone "https://github.com/phantomdev-github/Guardian.git"
        cd ./Guardian
        npm i
      env:
        CI: true
